### PR TITLE
Update v9

### PR DESCRIPTION
**Pull request by jals-es**
Update all methods to v9 according to the migration guide https://engineering.toggl.com/docs/additional/v8_migration_guide

### CODE REVIEW

**Review by elimentz — APPROVED** [review]

**Comment by elimentz** [comment]
Thanks so much, good work!

**Comment by jals-es** [comment]
Thanks @elimentz. I'm open to solving any issue that appears with these new changes. I have tested most of them and everything seems to be going well.

One last thing. Can you set a 1.3.0 version of the package?

**Comment by elimentz** [comment]
Can't do that, these are breaking changes so in accordance with semantic versioning, this would be v2.0.0

I won't make any promises (usually doesn't end well) but I'd like to do some testing myself as well and do some minor refactorings before I release a new version. I intend to do that this weekend, hopefully, so please bear with me for just a couple more days ;-)

**Comment by jals-es** [comment]
Ok, don't worry. At the moment, I can set the dev-master version and work with that. Thank you so much.

**Comment by elimentz** [comment]
@jals-es v2.0.0 is now released, which includes your recent changes. Thanks so much for contributing!!

**Comment by jals-es** [comment]
Thank you so much @elimentz

**Pull request merged**
